version: "3.2"
services:
  node:
    image: localhost:5000/demo-node:latest
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.port=3000"
        - "traefik.backend=node1-node"
        - "traefik.docker.network=traefik_web-net"
        - "traefik.frontend.rule=Host:node1.vicoders.com"
      restart_policy:
        condition: any
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]
      update_config:
        delay: 2s
      restart_policy:
        condition: on-failure

networks:
  default:
    external:
      name: traefik_web-net

volumes:
  nodedata:
