version: "3.2"
services:
  node:
    image: localhost:5000/demo-node:latest
      labels:
        - "traefik.enable=true"
        - "traefik.port=3000"
        - "traefik.backend=node1-node"
        - "traefik.docker.network=traefik_web-net"
        - "traefik.frontend.rule=Host:node1.vicoders.com"
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]

networks:
  default:
    external:
      name: traefik_web-net

volumes:
  nodedata:
