version: "3"
services:
  registry:
    image: registry:2
    volumes:
      - "./auth:/auth"
      - "./data:/var/lib/registry"
    environment:
      - REGISTRY_AUTH=htpasswd
      - "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm"
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
    ports:
      - "5000:5000"
    deploy:
      restart_policy:
        condition: any
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        delay: 2s
      restart_policy:
        condition: on-failure