version: "3.2"
services:
  nodejs:
    image: localhost:5000/node-server:latest
    deploy:
      labels:
        - "traefik.backend=nodejs"
        - "traefik.docker.network=webgateway"
        - "traefik.frontend.rule=Host:nodejs.vicoders.com"
        - "traefik.enable=true"
        - "traefik.port=3000"
      restart_policy:
        condition: any
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.name == nodejs]
      update_config:
        delay: 2s
      restart_policy:
        condition: on-failure

networks:
  webgateway:
    external: true

volumes:
  nodedata:
