version: "3.2"
services:
  nodejs:
    image: localhost:5000/mii:latest
    deploy:
      labels:
        - "traefik.backend=node1nodejs"
        - "traefik.docker.network=mystack_traefik-net"
        - "traefik.frontend.rule=Host:node1.traefik.kb"
        - "traefik.enable=true"
        - "traefik.port=3000"
      restart_policy:
        condition: any
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]
      update_config:
        delay: 2s
      restart_policy:
        condition: on-failure
networks:
  default:
    external:
      name: mystack_traefik-net

volumes:
  nodedata:
