version: "3.2"
services:
  nodejs:
    image: localhost:5000/node-server:latest
    volumes:
      - "nodedata:/usr/src/app/upload"
    deploy:
      labels:
        - "traefik.backend=noder-server"
        - "traefik.frontend.rule=Host:node.vicoders.com"
        - "traefik.enable=true"
        - "traefik.port=3000"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.frontend.entryPoints=http,https"
      restart_policy:
        condition: any
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]
      update_config:
        delay: 2s
      restart_policy:
        condition: on-failure

networks:
  default:
    external:
      name: webgateway

volumes:
  nodedata:
