version: "3.2"
services:
  node1:
    image: localhost:5000/mii:latest
    networks:
      - web-net
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.port=3000"
        - "traefik.docker.network=web-net"
        - "traefik.frontend.rule=Host:node1.vicoders.com"
      restart_policy:
        condition: any
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]
      update_config:
        delay: 2s
      restart_policy:
        condition: on-failure

networks:
  default:
    external:
      name: web-net

volumes:
  nodedata:
