version: "3.2"
services:
  nodejs:
    image: localhost:5000/mii:latest
    ports:
      - 3000
    deploy:
      labels:
        - "traefik.backend=mii"
        - "traefik.networks=webgateway"
        - "traefik.domain=vicoders.com"
        - "traefik.frontend.rule=Host:node1.vicoders.com"
        - "traefik.enable=true"
        - "traefik.port=3000"
      restart_policy:
        condition: any
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]
      update_config:
        delay: 2s
      restart_policy:
        condition: on-failure
networks:
  default:
    external:
      name: webgateway

volumes:
  nodedata:
