version: "3.2"
services:
  nodejs:
    image: localhost:5000/mii:latest
    expose:
      - "3000"
    deploy:
      labels:
        - "traefik.backend=nodejs"
        - "traefik.networks=webgateway"
        - "traefik.frontend.rule=Host:mii.vicoders.com"
        - "traefik.enable=true"
        - "traefik.port=3000"
      restart_policy:
        condition: any
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        delay: 2s
      restart_policy:
        condition: on-failure
networks:
  default:
    external:
      name: webgateway

volumes:
  nodedata:
