version: "3.2"
services:
  nodejs:
    image: localhost:5000/node-server:latest
    volumes:
      - "nodedata:/usr/src/app/upload"
    networks:
      - nodejs
      - webgateway
    ports:
      - target: 3000
        published: 3000
    deploy:
      labels:
        - "traefik.frontend.rule=Host:node1.node.vicoders.com"
        - "traefik.port=3000"
      restart_policy:
        condition: any
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]
      update_config:
        delay: 2s
      restart_policy:
        condition: on-failure

networks:
  webgateway:
    external:
      name: webgateway
  nodejs:
    driver: overlay

volumes:
  nodedata:
