version: "3"
services:
  nodejs:
    image: localhost:5000/node-server:latest
    networks:
      - nodejs
    volumes:
      - "nodedata:./upload"
    deploy:
      restart_policy:
        condition: any
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]
      update_config:
        delay: 2s
      restart_policy:
        condition: on-failure

networks:
  nodejs:

volumes:
  nodedata:
