version: "3.5"
services:
  traefik:
    image: traefik
    command: --web \
      --docker \
      --docker.swarmmode \
      --docker.domain=vicoders.com \
      --docker.watch \
      --logLevel=DEBUG
    networks:
      - web-net
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 8080
        published: 8080
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    deploy:
      mode: global
      placement:
        constraints: [node.role==manager]

networks:
  web-net:
    driver: overlay
    internal: true
