version: "3.3"
services:
  traefik:
    image: traefik
    command: --web \
      --docker \
      --docker.swarmmode \
      --docker.domain=traefik.kb \
      --docker.watch \
      --logLevel=DEBUG
    networks:
      - traefik-net
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    deploy:
      placement:
        constraints: [node.role==manager]
 
  portainer:
    image: portainer/portainer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainerdata:/data"
    networks:
      - traefik-net
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.port=9000"
        - "traefik.docker.network=mystack_traefik-net"
        - "traefik.frontend.rule=Host:portainer.traefik.kb"
 
  ms1:
    image: melvindave/spring-boot-example
    networks:
      - traefik-net
    depends_on:
      - mongodb
    deploy:
      replicas: 3
      labels:
        - "traefik.enable=true"
        - "traefik.port=8080"
        - "traefik.docker.network=mystack_traefik-net"
        - "traefik.frontend.rule=Host:ms1.traefik.kb"
  nodejs:
    image: localhost:5000/mii:latest
    deploy:
      labels:
        - "traefik.docker.network=mystack_traefik-net"
        - "traefik.frontend.rule=Host:node1.traefik.kb"
        - "traefik.enable=true"
        - "traefik.port=3000"
      restart_policy:
        condition: any
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]
      update_config:
        delay: 2s
      restart_policy:
        condition: on-failure

  mongodb:
    image: mongo
    volumes:
      - "mongodata:/data/db"
    networks:
      - traefik-net
    deploy:
      replicas: 1
    ports:
      - "27017:27017"  
 
networks:
  traefik-net:
 
volumes:
   portainerdata:
   mongodata: