version: "3.5"
services:
  traefik:
    image: traefik
    command: --web \
      --docker \
      --docker.swarmmode \
      --docker.domain=vicoders.com \
      --docker.watch \
      --logLevel=DEBUG
    networks:
      - web-net
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    deploy:
      placement:
        constraints: [node.role==manager]
 
  portainer:
    image: portainer/portainer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainerdata:/data"
    networks:
      - web-net
    deploy:
      placement:
        constraints: [node.role == worker]
      labels:
        - "traefik.enable=true"
        - "traefik.port=9000"
        - "traefik.docker.network=web-net"
        - "traefik.frontend.rule=Host:portainer.vicoders.com"
 
  ms1:
    image: melvindave/spring-boot-example
    networks:
      - web-net
    depends_on:
      - mongodb
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]
      labels:
        - "traefik.enable=true"
        - "traefik.port=8080"
        - "traefik.docker.network=web-net"
        - "traefik.frontend.rule=Host:ms1.vicoders.com"

  mongodb:
    image: mongo
    volumes:
      - "mongodata:/data/db"
    networks:
      - web-net
    deploy:
      replicas: 1
    ports:
      - "27017:27017"  
 
networks:
  web-net:
    driver: overlay

volumes:
   portainerdata:
   mongodata: