version: "3"

services:
  app:
    image: traefik:v1.6.5
    networks:
      - webgateway
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik/traefik.toml:/etc/traefik/traefik.toml
      - $PWD/traefik/acme:/etc/traefik/acme
    ports:
      - 80:80
      - 443:443
      - 8100:8080
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  webgateway:
    driver: overlay
    external: true
