debug = false
logLevel = "ERROR"

defaultEntryPoints = ["http", "https"]


[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "vicoders.com"
watch = true
exposedbydefault = false

[acme]
email = "xuankhu1111@gmail.com"
storageFile = "acme.json"
entryPoint = "https"
OnHostRule = true
[acme.httpChallenge]
entryPoint = "http"