version: "3.5"
services:
  traefik:
    image: traefik
    command: --web \
      --docker \
      --docker.swarmmode
    networks:
      - web-net
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme:/etc/traefik/acme.json
    configs:
      - source: traefik-config
        target: /etc/traefik/traefik.toml
    deploy:
      placement:
        constraints: [node.role==manager]

networks:
  web-net:
    driver: overlay
    internal: true

configs:
  traefik-config:
    file: traefik.toml
