version: "3.5"
services:
  traefik:
    image: traefik
    command: --web \
      --docker \
      --docker.swarmmode \
      --docker.domain=vicoders.com \
      --docker.watch \
      --logLevel=DEBUG
    networks:
      - web-net
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme:/etc/traefik/acme
    deploy:
      placement:
        constraints: [node.role==manager]

networks:
  web-net:
    driver: overlay
    internal: true
