version: "3.3"
services:
  laravel:
    build:
      context: .
      args:
        URL: ${URL}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_MASTER_HOST: 172.17.0.3
    container_name: web_laravel
    volumes:
      - dbdata:/var/www/workspace
    restart: always
    networks:
      laravel:
        ipv4_address: 172.17.0.2
    ports:
      - 80:80
      - 443:443

  # The Database
  mysql:
    image: "bitnami/mysql:5.7-ol-7"
    ports:
      - "3306:3306"
    volumes:
      - "mysql_data:/bitnami/mysql/data"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_MASTER_HOST=${MYSQL_MASTER_HOST}
    networks:
      laravel:
        ipv4_address: 172.17.0.3

volumes:
  mysql_data:
    driver: local
  dbdata:

network:
  laravel:
    driver: bridge
    ipam:
      config:
        - subnet: 172.17.0.0/16
          gateway: 172.17.0.1
